apiVersion: v1
kind: Service
metadata:
  name: colletor-nlb
  namespace : collector
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 30001
      nodePort: 30001
  type: LoadBalancer
