apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace : collector 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      serviceAccountName: collector-access-db
      containers:
      - name: collector
        image: 390844761387.dkr.ecr.ap-northeast-2.amazonaws.com/collector:v1.17
        imagePullPolicy: Always
