apiVersion: v1
kind: Service
metadata:
  name: bluegreen-nlb
  namespace : bluegreen
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 30009
      targetPort: 30009
      nodePort: 30009
  type: LoadBalancer
